### PR TITLE
Refactor into set of scripts

### PR DESCRIPTION
**Pull request by tkkuehn**
This PR makes afids-CNN runnable from the command line, with both training and application.

When built and installed, the following BIDS apps will be available (there are also a couple of scripts to train/apply on one file):

- `auto_afids_cnn_train_bids`: Takes a set of T1w images and ground truth fcsvs for training.
- `auto_afids_cnn_apply_bids`: Takes a set of T1w images and a model file, and produces an fcsv for each.

Once this has been reviewed, I can build and push this to PyPI so it can be `pip install`ed (with the note that the training side still needs c3d installed.

### CODE REVIEW

**Comment by tkkuehn** [comment]
I'm not sure why GitHub has so much trouble with the diff, but take a look at https://github.com/tkkuehn/afids-CNN/tree/snakebids to see the files themselves.

**Comment by kaitj** [comment]
Went through this as best as I could, hopefully I didn't miss any files. Mostly looks good to me, with just a few comments (more for discussion than requesting of changes)

### `generator.py`
  - This looks like it is based on someone else's code, but is it worth adding some warning messages for the try-except blocks?
  - On github, it looks like there are about 15 empty lines at the end of the file.

### `apply.py`
  - The methods `load_fcsv`, `get_fid`, `fid_voxel2world`, `fid_world2voxel`, `min_max_normalize`, `gen_patch_slices`, `slice_img`, `predict_distances`, `process_distances`, is probably better suited for `utils.py` / split into a separate module (also can see the benefit of moving these to an `afids-tools/afids-utils` repo since these are reused often). 
  - Minor comment, but would be good to get some docstrings to note the difference between `apply_afid_model` and `apply_model`

### `apply_all.py`
  - Is it worth consolidating this with `apply.py` since this ends up calling the method there?

### train_workflow
  - The `desc` entity for the patches is pretty long - is it worth considering a shorter entity and having these params in a json sidecar in the future?

**Comment by tkkuehn** [comment]
> ### `generator.py`
> 
> * This looks like it is based on someone else's code, but is it worth adding some warning messages for the try-except blocks?
> 
> * On github, it looks like there are about 15 empty lines at the end of the file.

Yeah, I didn't touch this file at all, so it's exactly as it is on `main` right now. I can clear up these couple of issues, in any case.

> ### `apply.py`
> 
> * The methods `load_fcsv`, `get_fid`, `fid_voxel2world`, `fid_world2voxel`, `min_max_normalize`, `gen_patch_slices`, `slice_img`, `predict_distances`, `process_distances`, is probably better suited for `utils.py` / split into a separate module (also can see the benefit of moving these to an `afids-tools/afids-utils` repo since these are reused often).

Agreed, it's on my to-do list to start an `afids-utils` (or `pyafids` or something) repo to hold all these kinds of functions.

> * Minor comment, but would be good to get some docstrings to note the difference between `apply_afid_model` and `apply_model`

Ah good catch, I meant to revisit the naming of these.

> ### `apply_all.py`
> 
> * Is it worth consolidating this with `apply.py` since this ends up calling the method there?

Probably. I don't think the `main()` in `apply.py` would ever be used, so may as well get rid of it.

> ### train_workflow
> 
> * The `desc` entity for the patches is pretty long - is it worth considering a shorter entity and having these params in a json sidecar in the future?

This is primarily to ensure that snakemake doesn't reuse old models if you're tuning hyperparameters, an issue I ran into in december with the c3d-based stuff. It's a little awkward to deal with but worth it imo.

**Comment by kaitj** [comment]
That sounds good, I can do another review afterwards. I can start throwing together an `afids-utils` based off of afids-regRF so that we have it. Some of the stuff is reused anyways.

**Comment by tkkuehn** [comment]
This is ready for another look. I left the code that's destined for `afids-utils` until that repo is ready to go.

**Review by kaitj — APPROVED** [review]
Lgtm. Still not sure why github is having so much trouble with the diff. It worked briefly for like 5 minutes this morning.

**Pull request merged**
